[project]
name = "NumpyAndStatsFun"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rahul Dave <rahuldave@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
pandas = ">=2.2.2,<2.3"
scipy = ">=1.13.0,<1.14"
python = ">=3.12.3,<3.13"
numpy = ">=1.26.4,<1.27"
jupyter = ">=1.0.0,<1.1"
matplotlib = ">=3.8.4,<3.9"
